# Generated by Django 5.0.7 on 2024-08-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_options_remove_persona_fb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
