# Generated by Django 5.0.7 on 2024-08-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_desc_service_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.FileField(default='user.jpg', upload_to='Testimonals')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
