# Generated by Django 5.0.7 on 2024-08-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_testimonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='services'),
        ),
    ]
