# Generated by Django 5.0.7 on 2024-08-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_img_alter_service_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='product_image',
        ),
    ]
