# Generated by Django 5.1 on 2024-08-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tw_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
