# Generated by Django 5.1 on 2024-08-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_persona_tw_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
